### ISSUE TITLE
zsh PROMPT is not well displayed when user has a customized Prompt with 2 lines

### ISSUE THREAD

**Issue by sbrun** [infobyte/faraday-client#1]
* Faraday GTK Client version: 1.0.0
* Python version: 3.8.4rc1
* Operating System: Kali

### Description
The PROMPT display is not looking as expecting  when the user has a customized zsh PROMPT with 2 lines, like we have in Kali.
We have this in the Kali default .zshrc:
```
PROMPT=$'%F{%(#.blue.green)}┌──${debian_chroot:+($debian_chroot)──}(%B%F{%(#.red.blue)}%n%(#.💀.㉿)%m%b%F{%(#.blue.green)})-[%B%F{reset}%(6~.%-1~/…/%4~.%5~)%b%F{%(#.blue.green)}]\n└─%B%(#.%F{red}#.%F{blue}$)%b%F{reset} '
```
The ┌── and └─ are not aligned correctly in the Faraday zsh terminal.

We have something like this:
```
[faraday] (workspace) ┌──(user@machine)[~]
└─$ 
```

**Comment by llazzaro** [comment]
Hi @sbrun,

This has been fixed at commit 6bcf44b79e5e0c7bb41e5ee4a0a8820ac15ad6bc.

![kali_fix](https://user-images.githubusercontent.com/568181/89113373-ac325380-d446-11ea-8c82-b9b6addb9736.PNG)

New version tagged v1.0.1
